Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2019-04, with the labels that each got.

#247 235-add-delete-change-get-teachers
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/controller/TeacherController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/TeacherRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/TeacherService.java
Labels: new feature

#252 222 - department
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/controller/DepartmentController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/specialization/SpecializationController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/DepartmentRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/DataVerificationService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/DepartmentService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/SpecializationService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/security/FacultyAuthorizationService.java
Labels: new feature

#253 250 issue bug/bug form rating
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/journal/FormRatingService.java
Labels: bug

#259 258 new feature/debtor report export
  api/src/main/java/ua/edu/chdtu/deanoffice/api/report/debtor/DebtorReportController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/report/debtor/DebtorReportExport.java
  core/src/main/resources/docs/templates/StudentPerformanceAnalysis.docx
Labels: new feature

#255 248 enhance/teachetrs check parameters
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/PositionRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/TeacherRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/DataVerificationService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/PositionService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/TeacherService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/security/FacultyAuthorizationService.java
Labels: enhancement

#262 #261 courses: enhancement: getAllCourses()
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/CourseService.java
Labels: enhancement

#263 251 bug/fix finish study year(#207)
  api/src/main/java/ua/edu/chdtu/deanoffice/api/studyyear/finish/StudyYearFinishController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/StudentExpelService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/study/year/finish/StudyYearFinishService.java
Labels: bug

#265 257 issue enhance/improve display items
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/journal/FormRatingService.java
Labels: enhancement

#269 260 an employee of the dean's office may change the student's surname by order
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/StudentSurnameChangeController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/dto/SpecialityDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/dto/SpecializationDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/dto/StudentDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/dto/StudentDegreeDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/dto/StudentSurnameChangeInputDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/dto/StudentSurnameChangeOutputDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/StudentSurnameChange.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/StudentSurnameChangeRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/order/StudentSurnameChangeService.java
  core/src/main/resources/db/migration/V28__create_table_student_surname_change.sql
Labels: new feature
