Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2019-11, with the labels that each got.

#368 #366 no expel data for academic reference: fix bug
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/academic/reference/AcademicReferenceService.java
Labels: bug

#369 #367 not enough space for faculty and group name:bug fix.
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/ssc/SingleStudentAndCourseExamReportService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/util/FacultyUtil.java
Labels: Doc Team, bug

#374 #347 older graduates group for diploma supplement: develop: change gr…
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/StudentGroupRepository.java
Labels: UX Team, enhancement

#364 #356 teacher service aspects for faculty authorization: refactor: add…
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/Teacher.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/FacultyRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/security/FacultyAuthorizationAspects.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/TeacherService.java
Labels: UX Team, refactoring

#375 365 complement feature/enhance deptors report
  api/src/main/java/ua/edu/chdtu/deanoffice/api/report/debtor/SpecializationDebtorsYearStatisticsDto.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/report/debtor/DebtorReportExport.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/report/debtor/DebtorReportService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/report/debtor/SpecializationDebtorsYearBean.java
  core/src/main/resources/docs/templates/StudentPerformanceAnalysis.docx
Labels: complement feature

#378 #308 feat/create wrapper for personal records
  api/src/main/java/ua/edu/chdtu/deanoffice/api/document/personalstatement/PersonalStatementController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/GradeRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/StudentAcademicVacationRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/GradeService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/StudentAcademicVacationService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/personalstatement/PersonalStatementService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/personalstatement/reports/AcademicVacationReport.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/personalstatement/reports/PracticeReport.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/personalstatement/reports/QualificationReport.java
  core/src/main/java/ua/edu/chdtu/deanoffice/util/DateUtil.java
  core/src/main/java/ua/edu/chdtu/deanoffice/util/StringUtil.java
  core/src/main/resources/docs/templates/PersonalWrapperBack.docx
  core/src/main/resources/docs/templates/PersonalWrapperFront.docx
Labels: Doc Team, new feature

#379 307 feat/export stipend info
  api/build.gradle
  api/src/main/java/ua/edu/chdtu/deanoffice/api/student/stipend/CourseForStipendDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/student/stipend/StipendController.java
  core/build.gradle
  core/src/main/java/ua/edu/chdtu/deanoffice/service/stipend/CourseForStipendBean.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/stipend/DebtorStudentDegreesBean.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/stipend/StipendService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/stipend/StudentInfoForStipend.java
  core/src/main/java/ua/edu/chdtu/deanoffice/util/SemesterUtil.java
  core/src/main/resources/docs/templates/FacultyStipendList.docx
Labels: Doc Team, new feature

#383 #381 dean-in-qw: fix: dean name, step on next sheet, student visible
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/QualificationWorkReportService.java
Labels: bug
