Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2019-10, with the labels that each got.

#345 #311 specialization restore: add: add controller and service
  api/src/main/java/ua/edu/chdtu/deanoffice/api/specialization/SpecializationController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/DataVerificationService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/SpecializationService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/security/FacultyAuthorizationService.java
Labels: UX Team, new feature

#348 301 feat/department for foreign students
  core/src/main/java/ua/edu/chdtu/deanoffice/Constants.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/DepartmentRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/DepartmentService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/diploma/supplement/SupplementTemplateFillService.java
Labels: complement feature

#353 215 refactor/faculty authorization with aspects
  api/build.gradle
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/ExceptionToHttpCodeMapUtil.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/controller/DepartmentController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/specialization/SpecializationController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/webstarter/Application.java
  api/src/main/java/ua/edu/chdtu/deanoffice/webstarter/security/JWTAuthenticationFilter.java
  api/src/main/java/ua/edu/chdtu/deanoffice/webstarter/security/JWTAuthorizationFilter.java
  core/build.gradle
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/Department.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/FacultyRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/security/FacultyAuthorizationAspects.java
  core/src/main/java/ua/edu/chdtu/deanoffice/security/FacultyAuthorized.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/DepartmentService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/util/FacultyUtil.java
Labels: refactoring

#355 #344 add english course name: develop: add DTO and set eng name to en…
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/CourseController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/dto/CourseDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/dto/NamedWithEngDTO.java
Labels: complement feature

#360 279 feat/create document of student progress
  api/src/main/java/ua/edu/chdtu/deanoffice/api/document/examreport/SingleStudentAndCourseExamReportController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/document/examreport/StudentCourseDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/ssc/BackSideConfig.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/ssc/SingleStudentAndCourseExamReportService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/ssc/StudentCourse.java
Labels: new feature

#361 337 fix/consolidated report document
  api/src/main/java/ua/edu/chdtu/deanoffice/api/document/examreport/ConsolidatedExamReportController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/document/examreport/multigroup/MultiGroupExamReportController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/ConsolidatedReportService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/ExamReportBaseService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/ExamReportTemplateFillService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/MultiGroupExamReportService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/MultiGroupReportTemplateFillService.java
  core/src/main/resources/docs/templates/MultiGroupExamReport.docx
  core/src/main/resources/docs/templates/SingleGroupStatement.docx
  core/src/test/java/ua/edu/chdtu/deanoffice/entity/EducationDocumentTest.java
  core/src/test/java/ua/edu/chdtu/deanoffice/util/PersonUtilTest.java
Labels: complement feature

#362 318 feat/statement of qualification work
  api/src/main/java/ua/edu/chdtu/deanoffice/api/document/examreport/QualificationWorkReportController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/QualificationWorkReportService.java
  core/src/main/resources/docs/templates/AbstractScholasticRecords.docx
Labels: Doc Team, new feature
