Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2019-02, with the labels that each got.

#182 Student previous university synchronization
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/mapper/Mapper.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/student/synchronization/edebo/SyncronizationController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/student/synchronization/edebo/dto/StudentDegreeFullEdeboDataDto.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/student/synchronization/edebo/dto/StudentPreviousUniversityDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/datasync/edebo/student/EdeboStudentDataSynchronizationServiceImpl.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/datasync/edebo/student/EdeboStudentDataSyncronizationService.java
Labels: new feature

#187 Student chess rating bagFix
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/Course.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/CourseService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/diploma/supplement/StudentSummary.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/groupgrade/StudentSummaryForGroup.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/groupgrade/SummaryForGroupService.java
Labels: bug

#190 Add specialization code field to SpecializationDTO
  api/src/main/java/ua/edu/chdtu/deanoffice/api/specialization/dto/SpecializationDTO.java
Labels: enhancement

#192 Fix renewed academic vacation student
  api/src/main/java/ua/edu/chdtu/deanoffice/api/student/dto/RenewedAcademicVacationStudentDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/RenewedAcademicVacationStudent.java
Labels: bug

#194 Create route that get all active speciality
  api/src/main/java/ua/edu/chdtu/deanoffice/api/speciality/SpecialityController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/SpecialityRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/SpecialityService.java
Labels: enhancement

#200 Create validation for DeleteCourseForGroups that check grades
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/CourseController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/CourseForGroupRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/CourseForGroupService.java
Labels: enhancement

#205 Change ResponseEntity output
  api/src/main/java/ua/edu/chdtu/deanoffice/api/group/GroupController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/group/dto/StudentGroupDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/specialization/SpecializationController.java
Labels: enhancement
