Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2019-12, with the labels that each got.

#385 380 bug/correct elements output
  core/src/main/java/ua/edu/chdtu/deanoffice/service/stipend/StipendService.java
  core/src/main/resources/docs/templates/FacultyStipendList.docx
Labels: bug

#386 #384 rows-in-qw: fix: intent between rows
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/report/exam/QualificationWorkReportService.java
Labels: Doc Team, bug

#377 #325 students average grades for year
  api/src/main/java/ua/edu/chdtu/deanoffice/api/report/averagegrades/AverageGradesInYearController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/report/averagegrades/dto/StudentsAveragePointsForYearDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/student/stipend/StipendController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/StudentDegreeRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/report/averagegrades/AverageGradesInYearService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/report/averagegrades/StudentsAveragePointsForYearBean.java
Labels: UX Team, new feature

#292 266 feat/user roles
  api/src/main/java/ua/edu/chdtu/deanoffice/api/specialization/SpecializationController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/webstarter/Application.java
  api/src/main/java/ua/edu/chdtu/deanoffice/webstarter/security/CurrentUserDetails.java
  api/src/main/java/ua/edu/chdtu/deanoffice/webstarter/security/JWTAuthenticationFilter.java
  api/src/main/java/ua/edu/chdtu/deanoffice/webstarter/security/JWTAuthorizationFilter.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/ApplicationUser.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/Role.java
  core/src/main/resources/db/migration/V31__create_user_roles_tabels.sql
Labels: new feature

#387 306 feat/periods of study at university
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/StudentPreviousUniversity.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/RenewedExpelledStudentRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/RenewedExpelledStudentService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/diploma/supplement/SupplementTemplateFillService.java
  core/src/main/resources/db/migration/V31__add_university_name_eng.sql
  core/src/main/resources/docs/templates/DiplomaSupplement.docx
Labels: Doc Team, complement feature
