Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2020-11, with the labels that each got.

#453 #452 selective course: fix: number of character in field description
  core/src/main/resources/db/migration/V37__add_selective_courses.sql
Labels: SelectiveCoursesTeam, bug

#454 443 new feature selective course
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/SelectiveCourseController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/dto/SelectiveCoursesStudentDegreeDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/dto/SelectiveCoursesStudentDegreeWriteDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/SelectiveCoursesStudentDegrees.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/SelectiveCoursesStudentDegreesRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/StudentDegreeService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/SelectiveCourseConstants.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/SelectiveCourseService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/SelectiveCoursesStudentDegreesService.java
Labels: SelectiveCoursesTeam, new feature

#455 444 feat/selective course
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/FieldOfKnowledgeController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/SelectiveCourseController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/dto/SelectiveCourseDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/dto/SelectiveCourseStudentDegreesDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/dto/StudentDegreeDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/dto/FieldOfKnowledgeDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/specialization/dto/SpecializationDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/student/dto/StudentView.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/SelectiveCourse.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/SelectiveCoursesStudentDegreesRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/SelectiveCoursesStudentDegreesService.java
  core/src/main/resources/db/migration/V37__add_selective_courses.sql
Labels: SelectiveCoursesTeam

#456 450 enhance/individual curriculum
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/SelectiveCoursesStudentDegreesRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/SelectiveCoursesStudentDegreesService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/document/individualcurriculum/IndividualCurriculumFillTemplateService.java
  core/src/main/resources/docs/templates/IndividualCurriculum.docx
Labels: enhancement
