Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2020-04, with the labels that each got.

#397 #329 specializationController: add: access right
  api/src/main/java/ua/edu/chdtu/deanoffice/api/specialization/SpecializationController.java
Labels: UX Team, new feature

#372 #334-feat/add_tuition_form_term_to_student_degree
  .gitignore
  api/src/test/java/ua/edu/chdtu/deanoffice/TestFeatureDiplomaSupplement.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/StudentDegree.java
  core/src/main/resources/db/migration/V34__add-tuition_form_and_term_to_student_degree.sql
Labels: UX Team, complement feature

#389 #326 Scientific Degree Directory: add: ScientificDegree.java, Scienti…
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/controller/ScientificDegreeController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/NewTeacherDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/ScientificDegreeDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/NewTeacher.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/ScientificDegree.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/ScientificDegreeRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/ScientificDegreeService.java
  core/src/main/resources/db/migration/V35__create_scientific_degrees_table.sql
Labels: UX Team, enhancement
