Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2020-05, with the labels that each got.

#408 403 feat/teacher scientific degree join
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/dto/validation/ExistingIdDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/general/dto/validation/NullAllowedExistingIdDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/NewTeacherDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherBasicDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherInsertDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/teacher/TeacherUpdateDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/AcademicTitle.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/Teacher.java
  core/src/main/java/ua/edu/chdtu/deanoffice/security/FacultyAuthorizationAspects.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/DataVerificationService.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/TeacherService.java
  core/src/main/resources/db/migration/V35__create_scientific_degrees_table.sql
Labels: Doc Team, complement feature

#413 410 new feature order approver
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/OrderApproverController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/dto/OrderApproverDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/order/OrderApprover.java
  core/src/main/java/ua/edu/chdtu/deanoffice/entity/order/SingleApprover.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/order/OrderApproverRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/order/OrderApproverService.java
Labels: new feature

#419 #416 create order approver: refactor: set active true
  core/src/main/java/ua/edu/chdtu/deanoffice/service/order/OrderApproverService.java
Labels: Orders Team, refactoring

#421 #417 order approver: complement: restore, show list not active approver
  api/src/main/java/ua/edu/chdtu/deanoffice/api/order/OrderApproverController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/order/OrderApproverRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/order/OrderApproverService.java
Labels: Orders Team, complement feature
