Repository chdtu-fitis/deanoffice-backend, pull requests merged in 2022-05, with the labels that each got.

#545 #544 selective course students percent: refactoring: SelectiveCourseStatisticsService
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/statistics/IStatisticsCondition.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/statistics/SelectiveCourseStatisticsService.java
Labels: refactoring

#553 509 complement/selective course group name generating
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/SelectiveCourseController.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/SelectiveCourseRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/SelectiveCourseService.java
Labels: new feature

#554 546 feat/appoint selective course
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/SelectiveCourseStatisticsController.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/dto/statistics/CoursesSelectedByStudentsGroupDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/dto/statistics/GroupStudentsRegistrationResultDTO.java
  api/src/main/java/ua/edu/chdtu/deanoffice/api/course/selective/dto/statistics/StudentNameAndIdDTO.java
  core/src/main/java/ua/edu/chdtu/deanoffice/repository/SelectiveCoursesStudentDegreesRepository.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/statistics/CourseSelectedByStudentsGroup.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/statistics/GroupStudentsRegistrationResult.java
  core/src/main/java/ua/edu/chdtu/deanoffice/service/course/selective/statistics/SelectiveCourseStatisticsService.java
Labels: complement feature
